# Generated by Django 3.0.7 on 2021-07-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210731_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essay',
            field=models.TextField(default='It will serve as a refreshing change to the status quo. I hope to create/engage w/ high-quality information.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.CharField(default='I developed this idea lol', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
