# Generated by Django 3.0.7 on 2021-08-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210825_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='participant_count',
            field=models.IntegerField(default=1),
        ),
    ]
