# Generated by Django 3.0.7 on 2021-07-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210731_0837'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verificationcode',
            table='verification_codes',
        ),
    ]
