# Generated by Django 3.0.7 on 2021-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210731_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
