# Generated by Django 3.0.7 on 2021-08-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210731_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
