# Generated by Django 3.0.7 on 2021-08-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_discussion_network_space'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discussion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='network',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='space',
            managers=[
            ],
        ),
    ]
