# Generated by Django 3.0.7 on 2021-08-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210808_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Network'),
        ),
    ]
