# Generated by Django 3.0.7 on 2021-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210808_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='link_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
