# Generated by Django 3.0.7 on 2021-08-08 07:14

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_discussion_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='audio',
            field=models.FileField(blank=True, upload_to=main.models.discussion_upload_to),
        ),
        migrations.AddField(
            model_name='discussion',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='main.User'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='main.Space'),
        ),
    ]
