# Generated by Django 3.0.7 on 2021-08-10 17:32

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210808_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='audio',
            field=models.FileField(upload_to=main.models.discussion_upload_to),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='main.User'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=main.models.response_upload_to)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('link_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_posts', to='main.Discussion')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_posts', to='main.User')),
            ],
            options={
                'db_table': 'response_posts',
            },
        ),
    ]
