# Generated by Django 3.0.7 on 2021-08-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210810_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='favorited_users',
            field=models.ManyToManyField(related_name='favorite_spaces', to='main.User'),
        ),
    ]
