# Generated by Django 3.0.7 on 2021-08-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_space_favorited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='saved_users',
            field=models.ManyToManyField(related_name='discussions_saved', to='main.User'),
        ),
    ]
