# Generated by Django 3.0.7 on 2021-08-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_discussion_saved_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_discussions', to='main.User'),
        ),
    ]
